---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04-fresh
  driver_config:
    box: precise64
    box_url: http://dl.dropbox.com/u/1537815/precise64.box
  run_list:
    - recipe[deploy-drupal::dependencies]
  attributes: {
    "mysql": {
      "server_root_password": "root",
      "server_debian_password": "root",
      "server_repl_password": "root"
    }
  }

suites:
- name: download-and-install-7
  run_list: 
  - recipe[deploy-drupal::default]
  - recipe[minitest-handler]
- name: download-populate-install
  run_list:
  - recipe[deploy-drupal::default]
  - recipe[minitest-handler]
  attributes: {
    "deploy-drupal" : {
      "dev_group" : "vagrant"
    },
    "minitest": {
      "recipes": ["deploy-drupal::default"]
    }
  }
- name: download-and-install-6
  run_list: 
  - recipe[deploy-drupal::default]
  - recipe[minitest-handler]
- name: download-populate-install
  run_list:
  - recipe[deploy-drupal::default]
  - recipe[minitest-handler]
  attributes: {
    "deploy-drupal" : {
      "dev_group" : "vagrant",
      "version" : "6"
    },
    "minitest": {
      "recipes": ["deploy-drupal::default"]
    }
  }

- name: get-project-path
  run_list:
  - recipe[deploy-drupal::default]
  - recipe[minitest-handler]
  attributes: {
    "deploy-drupal": {
      "dev_group" : "vagrant",
      "get_project" : { 
        "git" : "" ,
        "path" : "/vagrant/repo"
      },
    },
    "minitest": {
      "recipes": ["deploy-drupal::default"]
    }
  }
- name: get-project-git-with-dump
  run_list:
  - recipe[deploy-drupal::default]
  - recipe[minitest-handler]
  attributes: {
    "deploy-drupal": {
      "dev_group" : "vagrant",
      "get_project" : { 
        "git_repo" : "file:///vagrant/repo" , 
        "git_branch" : "foo" 
      },
      "install" : { 
        "sql_dump" : "db/sql_dump",
        "settings" : "settings-priv.php",
      },
    },
    "minitest": {
      "recipes": ["deploy-drupal::default"]
    }
  }
- name: nginx
  run_list:
  - recipe[deploy-drupal::default]
  - recipe[deploy-drupal::nginx]
  - recipe[minitest-handler]
  attributes: {
    "deploy-drupal": {
      "dev_group" : "vagrant",
      "apache_port" : "8000",
      "nginx" : { 
        "port": "80"
      },
    },
    "apache" : { 
      "listen_ports" : ["8000"]
    },
    "minitest": {
      "recipes": ["deploy-drupal::default", "deploy-drupal::nginx"]
    },
  }
