---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64

suites:
- name: default
  run_list: 
  - recipe[deploy_drupal]
  - recipe[minitest-handler]
  attributes: {
    "deploy_drupal": {
      "sql_load_file": "/vagrant/db/dump.sql.gz",
      "codebase_source_path": "/vagrant/site",
      "dev_group" : "sudo"
    },
    "mysql": {
      "server_root_password": "root",
      "server_debian_password": "root",
      "server_repl_password": "root"
    },
    "minitest": {
      "recipes": ["deploy_drupal"]
    }
  }
